[package]
name = "renderx"
version = "0.1.0"
authors = ["josephlenton@gmail.com <josephlenton@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
rsx_macro = {path = "./rsx_macro"}
rsx_parser = {path = "./rsx_parser"}
