[package]
name = "makro"
version = "0.1.0"
authors = ["Joseph Lenton <josephlenton@gmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
parser = {path = "./../parser"}
proc-macro2 = "1.0.24"

[dev-dependencies]
classnames = "2.1.1"
